appState={firstClick:0,numPenguins:0,totalScore:0};score=[];solution=[];$(document).ready(function(){$("#myModal").modal({show:!0});logButton()});
function onClick(){var a=$("#x").val();if(1<=a&&9>=a){$("#myModal").modal("hide");$("#msg").html("Make as many penguins eat food and then maximize the total score.");$("#msg2").html("");$("#modmsg").html("Select a worksheet (Easy: 1-3, Medium: 4-6, Hard: 7-9) and click 'Generate Worksheet'.");appState.firstClick=0;appState.numPenguins=0;appState.totalScore=0;var b=new XMLHttpRequest;b.onreadystatechange=function(){if(4==b.readyState&&200==b.status){var a=JSON.parse(b.responseText);saveScores(a.L.length,
a.R.length,a.E);makeTable(a.L,a.R);drawEdges(a.L.length,a.R.length);processGame()}4==b.readyState&&400==b.status&&$("#msg").html("Invalid request")};b.open("GET","matching.php?cmd=generate&graph_id="+a,!0);b.send()}else $("#modmsg").html("Please select X from 1 to 9.")}function logButton(){var a=new XMLHttpRequest;a.onreadystatechange=function(){if(4==a.readyState&&200==a.status){var b=a.responseText;$("#inout").html(b)}};a.open("GET","matching.php?cmd=log",!0);a.send()}
function login(){var a=new XMLHttpRequest;a.onreadystatechange=function(){4==a.readyState&&200==a.status&&("Login"==a.responseText?window.location.replace("login.php"):window.location.replace("logout.php"))};a.open("GET","matching.php?cmd=log",!0);a.send()}
function solve(){var a=$("#x").val(),b=JSON.stringify(solution),d=new XMLHttpRequest;d.onreadystatechange=function(){if(4==d.readyState&&200==d.status){var a=JSON.parse(d.responseText);1==a.new_best?$("#modmsg2").html("Your solution of "+appState.numPenguins+" penguins and "+appState.totalScore+" points is the highest so far.<br><br>Best recorded from our database:<br> Number of matches: "+a.num_match+"<br>Score: "+a.match_score+"<br>Best Time: "+a.best_time):$("#modmsg2").html("Your solution is NOT the highest so far. <br><br>Best recorded from our database:<br> Number of matches: "+
a.num_match+"<br>Score: "+a.match_score+"<br>Best Time: "+a.best_time+"<br>Reset and try again :(");getOptimal()}4==d.readyState&&400==d.status&&($("#msg").html("Invalid request"),$("#modmsg2").html("Invalid request"))};d.open("GET","matching.php?cmd=solve&graph_id="+a+"&solution="+b,!0);d.send()}
function getOptimal(){var a=$("#x").val(),b=new XMLHttpRequest;b.onreadystatechange=function(){if(4==b.readyState&&200==b.status){var a=JSON.parse(b.responseText);a.match_score==appState.totalScore&&a.num_match==appState.numPenguins?$("#modmsg3").html("<br>Congratulations. You found the optimal solution."):$("#modmsg3").html("<br>Sorry, you didn't find the optimal score.")}};b.open("GET","matching.php?cmd=solve&graph_id="+a,!0);b.send()}
function saveScores(a,b,d){score.splice(0,score.length);solution.splice(0,solution.length);for(var c=0;c<a;c++){score[c]=[];for(var e=0;e<b;e++)score[c].push(0)}for(c=0;c<d.length;c++)a=d[c][0],b=d[c][1],e=d[c][2],score[a][b]=e}
function makeTable(a,b){$("#tbl").empty();for(var d=Math.max(a.length,b.length),c=0;c<d;c++){var e=document.getElementById("tbl").insertRow(-1),g=e.insertCell(0);if(c>=a.length)g.setAttribute("class","col-xs-4 col-sm-4 col-md-4 enlarge");else{g.setAttribute("class","left col-xs-4 col-sm-4 col-md-4 enlarge");var f=document.createElement("IMG");f.setAttribute("src","penguin/"+a[c]+".png");768<=screen.width?f.setAttribute("class","big"):f.setAttribute("class","small");g.appendChild(f);g.setAttribute("id",
c)}0==c&&(f=e.insertCell(-1),f.setAttribute("class","col-xs-4 col-sm-4 col-md-4"),f.setAttribute("rowspan",d),f.setAttribute("id","midCol"),f=100*d,768<=screen.width?$("#midCol").html('<canvas id="cvs" width="300" height="'+f+'" ;"></canvas>'):$("#midCol").html('<canvas id="cvs" width="100" height="'+f+'" ;"></canvas>'));e=e.insertCell(-1);c>=b.length?e.setAttribute("class","col-xs-4 col-sm-4 col-md-4 enlarge"):(e.setAttribute("class","right col-xs-4 col-sm-4 col-md-4 enlarge"),f=document.createElement("IMG"),
f.setAttribute("src","food/"+b[c]+".png"),768<=screen.width?f.setAttribute("class","big"):f.setAttribute("class","small"),e.appendChild(f),e.setAttribute("id",c))}}
function processGame(){$("td").on("click",function(){var a,b,d,c,e;if(!$(this).hasClass("matched"))if(0==appState.firstClick)$(this).addClass("selected"),first=$(this),appState.firstClick=1;else{d=$(this);c=$(this).attr("id");e=$(this).attr("class").split(/\s+/)[0];a=first.attr("id");b=first.attr("class").split(/\s+/)[0];if(b==e)$("#msg").html("Match penguin with food.");else if("left"==b&&0!=score[a][c]||"right"==b&&0!=score[c][a])first.addClass("matched"),d.addClass("matched"),appState.numPenguins++,
"left"==b?(appState.totalScore+=score[a][c],drawLines(a,c,"red",4),a=[a,c]):(appState.totalScore+=score[c][a],drawLines(c,a,"red",4),a=[c,a]),solution.push(a),$("#msg").html("You have made "+appState.numPenguins+" penguin(s) eat with "+appState.totalScore+" points.");first.removeClass("selected");appState.firstClick=0}})}function drawEdges(a,b){for(var d=0;d<a;d++)for(var c=0;c<b;c++)0<score[d][c]&&(drawLines(d,c,"black",1),insertScore(d,c,score[d][c]))}
function drawLines(a,b,d,c){1>=Math.abs(a-b)?drawStraightLine(a,b,d,c):drawCurvyLine(a,b,d,c)}function drawStraightLine(a,b,d,c){var e=document.getElementById("cvs").getContext("2d");e.beginPath();768<=screen.width?(e.moveTo(0,100*a+50),e.lineTo(300,100*b+50)):(e.moveTo(0,100*a+50),e.lineTo(100,100*b+50));e.strokeStyle=d;e.lineWidth=c;e.stroke()}
function drawCurvyLine(a,b,d,c){var e=document.getElementById("cvs").getContext("2d");e.beginPath();768<=screen.width?(e.moveTo(0,100*a+50),e.bezierCurveTo(150,100*a+50,150,100*b+50,300,100*b+50)):(e.moveTo(0,100*a+50),e.bezierCurveTo(50,100*a+50,50,100*b+50,100,100*b+50));e.strokeStyle=d;e.lineWidth=c;e.stroke()}
function insertScore(a,b,d){var c=document.getElementById("cvs").getContext("2d");768<=screen.width?(c.font="16px Georgia",a>b+1?c.fillText(d,30,100*b+40):b>a+1?c.fillText(d,270,100*b+40):c.fillText(d,150,100*(a+b)/2+45)):(c.font="10px Georgia",a>b+1?c.fillText(d,20,100*b+45):b>a+1?c.fillText(d,80,100*b+45):c.fillText(d,50,100*(a+b)/2+45))};